require('modules.external_tools.pylint')
require('modules.external_tools.radon')
require('modules.external_tools.formatter')
require('modules.external_tools.markdown')
require('modules.external_tools.add_annotation')
